---
config:
  layout: fixed
---
flowchart LR
 subgraph Detection_Stream["Analisi Visuale"]
        Y_Knife("YOLO Knife Detection")
        Y_Pose("YOLO Pose Estimation")
  end
 subgraph Temporal_Stream["Analisi Temporale"]
        Tracker("Person Tracking")
        Buffer("Keypoints Buffer")
        LSTM("Violence LSTM Classifier")
  end
 subgraph s1["Legenda:"]
        L1("I/O")
        L2("Modelli AI")
        L3("Logica")
        L4("Strutture Dati")
  end
    Input("Input Video Frame") --> Y_Knife & Y_Pose
    Y_Pose --> Tracker
    Tracker --> Buffer
    Buffer --> LSTM
    Y_Knife --> Logic("Decision & Fusion Logic")
    LSTM --> Logic
    Logic --> Render("Visualization & Logging")
    Render --> Output("Annotated Output Frame")

     Y_Knife:::model
     Y_Pose:::model
     Tracker:::op
     Buffer:::data
     LSTM:::model
     L1:::video
     L2:::model
     L3:::op
     L4:::data
     Input:::video
     Logic:::op
     Render:::op
     Output:::video
    classDef video fill:#98dfba,stroke:#333,stroke-width:1px
    classDef op fill:#d7bde2,stroke:#333,stroke-width:1px
    classDef data fill:#9fa8da,stroke:#333,stroke-width:1px
    classDef model fill:#c0392b,stroke:#333,stroke-width:1px,color:white